<?php
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class THLogin_Admin {

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'register_admin_menu_page' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_admin_scripts' ) );
		add_action( 'admin_head', function () {
			$image_url = esc_url( plugins_url( '../assets/images/thlogin-new.svg', __FILE__ ) );

		// Inject inline CSS safely
		wp_add_inline_style( 'thlogin-admin-style', '
			#adminmenu .toplevel_page_thlogin-settings .wp-menu-image:before {
				content: "";
				display: inline-block;
				width: 20px;
				height: 20px;
				background-size: contain;
				background-repeat: no-repeat;
				background-position: center;
				background-image: url("' . esc_url( $image_url ) . '");
			}
			#adminmenu .toplevel_page_thlogin-settings .wp-menu-image img {
				display: none;
			}
		' );

		} );

	}

	public function register_admin_menu_page() {
		add_menu_page(
			esc_html__( 'Themehunk Login Registration', 'themehunk-login-registration' ), // Page title
			esc_html__( 'Themehunk Login Registration', 'themehunk-login-registration' ), // Menu title
			'manage_options',                     // Capability
			'thlogin-settings',                   // Slug
			array( $this, 'render_admin_page' ),  // Callback
			'',
			59
		);
	}

	public function render_admin_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return; // Security check.
		}
		?>
		 <div id="thlogin-admin-root" class="thlogin-admin-wrap wrap">
			<div class="thlogin-loader">
				<div class="thlogin-loader-circle"></div>
				<div class="thlogin-loader-circle"></div>
				<div class="thlogin-loader-circle"></div>
				<div class="thlogin-loader-circle"></div>
					<p class="thlogin-loading-text"><?php echo esc_html_e( 'Loading settings...', 'themehunk-login-registration' ); ?></p>
			</div>
		</div>
		<?php
	}

	public function enqueue_admin_scripts( $hook ) {
		if ( 'toplevel_page_thlogin-settings' !== $hook ) {
			return;
		}

		// Load asset file generated by WP scripts build
		$asset_file = THLOGIN_PATH . 'app/build/admin.asset.php';
		$asset_config = file_exists( $asset_file ) ? require_once $asset_file : array(
			'dependencies' => array(),
			'version'      => THLOGIN_VERSION,
		);

		wp_enqueue_style( 'wp-components' );
		wp_enqueue_media();
		wp_enqueue_script( 'wp-block-editor' );
		wp_enqueue_script( 'wp-edit-post' );
		wp_enqueue_style( 'wp-edit-blocks' );

		// Enqueue the admin.js file with defer
		wp_register_script(
			'thlogin-admin-script',
			THLOGIN_URL . 'app/build/admin.js',
			$asset_config['dependencies'],
			$asset_config['version'],
			array(
				'in_footer' => true,
				'strategy' => 'defer' // Using defer for better control
			)
		);

		wp_enqueue_script('thlogin-admin-script');

		// Enqueue the admin.css file
		wp_enqueue_style(
			'thlogin-admin-style',
			THLOGIN_URL . 'app/build/admin.css',
			array(),
			$asset_config['version']
		);

		$all_settings = get_option( 'thlogin_settings', array() );

		$settings_data = array(
			'general'          => $all_settings['general'] ?? array(),
			'design'           => $all_settings['design'] ?? array(),
			'form_fields'      => $all_settings['form_fields'] ?? array(),
			'display_triggers' => $all_settings['display_triggers'] ?? array(),
			'security'         => $all_settings['security'] ?? array(),
		);

		$woo_active  = class_exists('WooCommerce');
		$thlogin_page = get_page_by_path('th-login');
		$thlogin_url  = $thlogin_page ? get_permalink($thlogin_page) : '';

		$smtp_active =
			class_exists( 'WPMailSMTP\Options' )     // WP Mail SMTP
			|| class_exists( 'Postman' )             // Post SMTP
			|| class_exists( 'EasyWPSMTP\Main' )     // Easy WP SMTP (v2.x+)
			|| class_exists( 'EasyWPSMTP' )          // Easy WP SMTP (older fallback)
			|| class_exists( 'MailBank' );           // Mail Bank

		$integration_wp = $all_settings['integration']['wordpress'] ?? array();
		$wp_enabled     = ! empty( $integration_wp['enabled'] );
		$wp_custom_slug = sanitize_title( $integration_wp['url'] ?? 'login' );
		$wp_login_url   = $wp_enabled ? home_url( '/' . $wp_custom_slug ) : '';

		wp_localize_script(
			'thlogin-admin-script',
			'thLoginData',
			array(
				'root'      => esc_url_raw( rest_url( 'thlogin/v1/' ) ),
				'nonce'     => wp_create_nonce( 'wp_rest' ),
				'settings'  => $settings_data,
				'pluginUrl' => THLOGIN_URL,
				'siteUrl'   => get_site_url(),
				'ajaxUrl'   => admin_url( 'admin-ajax.php' ),
			)
		);

		wp_localize_script('thlogin-admin-script', 'thlogin_admin_data', array(
			'woo_enabled'   => $woo_active,
			'smtp_enabled'  => $smtp_active,
			'myaccount_url' => $woo_active ? wc_get_page_permalink('myaccount') : '',
			'thlogin_url'   => $thlogin_page ? $thlogin_url : '',
			'wp_login_url'  => $wp_login_url, 
			'base_url'      => home_url('/'),
			'admin_url'     => admin_url()
		));

	}
}