<?php
// Exit if accessed directly.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class THLogin_Admin {

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'register_admin_menu_page' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_admin_scripts' ) );
	}

	public function register_admin_menu_page() {
		add_menu_page(
			esc_html__( 'TH Login', 'th-login' ), // Page title
			esc_html__( 'TH Login', 'th-login' ), // Menu title
			'manage_options',                    // Capability required to access
			'thlogin-settings',                 // Menu slug
			array( $this, 'render_admin_page' ), // Callback function to render page content
			'dashicons-admin-users',             // Icon for the menu item
			59                                   // Position in the menu
		);
	}

	public function render_admin_page() {
		if ( ! current_user_can( 'manage_options' ) ) {
			return; // Security check.
		}
		?>
		<div id="thlogin-admin-root" class="wrap">
			<h1><?php echo esc_html__( 'TH Login Settings', 'th-login' ); ?></h1>
			<p><?php echo esc_html__( 'Loading settings...', 'th-login' ); ?></p>
		</div>
		<?php
	}

	public function enqueue_admin_scripts( $hook ) {
		if ( 'toplevel_page_thlogin-settings' !== $hook ) {
			return;
		}

		// Load asset file generated by WP scripts build
		$asset_file = THLOGIN_PATH . 'app/build/admin.asset.php';
		$asset_config = file_exists( $asset_file ) ? require_once $asset_file : array(
			'dependencies' => array(),
			'version'      => THLOGIN_VERSION,
		);

		wp_enqueue_style( 'wp-components' );
		wp_enqueue_media();
		wp_enqueue_script( 'wp-block-editor' );
		wp_enqueue_script( 'wp-edit-post' );
		wp_enqueue_style( 'wp-edit-blocks' );

		// Enqueue the admin.js file with defer
		wp_enqueue_script(
			'thlogin-admin-script',
			THLOGIN_URL . 'app/build/admin.js',
			$asset_config['dependencies'],
			$asset_config['version'],
			array(
				'in_footer' => true,
				'strategy' => 'defer' // Using defer for better control
			)
		);

		// Enqueue the admin.css file
		wp_enqueue_style(
			'thlogin-admin-style',
			THLOGIN_URL . 'app/build/admin.css',
			array(),
			$asset_config['version']
		);

		// Localize script with settings data
		$settings_data = array(
			'general'          => json_decode( get_option( 'thlogin_general_settings', '{}' ), true ),
			'design'           => json_decode( get_option( 'thlogin_design_settings', '{}' ), true ),
			'form_fields'      => json_decode( get_option( 'thlogin_form_fields_settings', '{}' ), true ),
			'display_triggers' => json_decode( get_option( 'thlogin_display_triggers_settings', '{}' ), true ),
			'security'         => json_decode( get_option( 'thlogin_security_settings', '{}' ), true ),
		);

		wp_localize_script(
			'thlogin-admin-script',
			'thLoginData',
			array(
				'root'      => esc_url_raw( rest_url( 'thlogin/v1/' ) ),
				'nonce'     => wp_create_nonce( 'wp_rest' ),
				'settings'  => $settings_data,
				'pluginUrl' => THLOGIN_URL,
				'siteUrl'   => get_site_url(),
				'ajaxUrl'   => admin_url( 'admin-ajax.php' ),
			)
		);

		$woo_active  = class_exists('WooCommerce');
		$thlogin_page = get_page_by_path('th-login');
		$thlogin_url  = $thlogin_page ? get_permalink($thlogin_page) : '';

		wp_localize_script('thlogin-admin-script', 'thlogin_admin_data', array(
			'woo_enabled'   => $woo_active,
			'myaccount_url' => $woo_active ? wc_get_page_permalink('myaccount') : '',
			'thlogin_url'   => $thlogin_page ? $thlogin_url : '',
		));

	}
}